# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-21 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20170921_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='num',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
