# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-21 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20170921_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='line',
        ),
        migrations.AddField(
            model_name='line',
            name='line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cms.Profile', to_field='user'),
            preserve_default=False,
        ),
    ]
