# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-21 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20170921_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='m1',
        ),
        migrations.AddField(
            model_name='line',
            name='line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cms.Profile', to_field='user'),
            preserve_default=False,
        ),
    ]
