# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-21 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20170921_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='m1',
            new_name='line',
        ),
    ]
